# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-SPOCP
version:      0.12
version_from: SPOCP.pm
installdirs:  site
requires:
    Authen::SASL::Cyrus:           0
    MIME::Base64:                  0
    Parse::Yapp:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
